# Generated by Django 5.0.3 on 2024-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shorten_url', models.URLField(unique=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
