# Generated by Django 5.0.3 on 2024-03-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
